<?php  if ( ! defined('BASEPATH')) exit('No direct script access allowed');

class Tag_model extends CI_Model
{
  public $table = 'tag';
  public $id    = 'id_tag';
  public $order = 'DESC';

  // get all
  function get_all()
  {
    return $this->db->get($this->table)->result();
  }

  function get_combo_tag()
  {
    $this->db->order_by('judul_tag', 'ASC');
    $query = $this->db->get($this->table);

    if($query->num_rows() > 0){
      $data = array();
      foreach ($query->result_array() as $row)
      {
        $data[$row['judul_tag']] = $row['judul_tag'];
      }
      return $data;
    }
  }

  function get_all_new_home()
  {
    $this->db->limit(4);
    $this->db->order_by($this->id, $this->order);
    return $this->db->get($this->table)->result();
  }

  function get_all_tag_sidebar()
  {
    $this->db->limit(14);
    $this->db->order_by('nama_tag', 'random');
    return $this->db->get($this->table)->result();
  }
  function get_all_random()
  {
    $this->db->limit(5);
    $this->db->order_by($this->id, 'random');
    return $this->db->get($this->table)->result();
  }
  function get_total_row_tag()
  {
    return $this->db->get($this->table)->count_all_results();
  }

  function get_by_id($id)
  {
    $this->db->where($this->id, $id);
    return $this->db->get($this->table)->row();
  }

  function get_by_id_front($id)
  {

    $this->db->limit(4);
    $this->db->from('berita');
    $this->db->where('tag_seo', $id);
    $this->db->order_by('id_berita', $this->order);
    $this->db->join('tag', 'berita.tag = tag.nama_tag');
    return $this->db->get();
  }
  function get_count_all_tag($id)
  {
      $tags = (explode(",",$tag->nama_tag));
	$this->db->where('tag_seo', $id);
	 $this->db->join('tag', 'berita.tag = tag.nama_tag');
	return $this->db->get('berita')->num_rows();

  }


  function get_by_id_front_paging($id, $number, $offset)
  {
   $this->db->where('tag_seo', $id);
   $this->db->order_by('id_berita', $this->order);
    $this->db->join('tag', 'berita.tag = tag.nama_tag');
    return $query = $this->db->get('berita',$number,$offset)->result();
  }

  // get total rows
  function total_rows()
  {
    return $this->db->get($this->table)->num_rows();
  }

  function insert($data)
  {
    $this->db->insert($this->table, $data);
  }

  function update($id, $data)
  {
    $this->db->where($this->id,$id);
    $this->db->update($this->table, $data);
  }

  function delete($id)
  {
    $this->db->where($this->id, $id);
    $this->db->delete($this->table);
  }

}

/* End of file tag_model.php */
/* Location: ./application/models/tag_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-10-17 02:19:21 */
/* http://harviacode.com */
